Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [60]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

iris = load_iris()

x = iris['data']
x.shape

mean = np.mean(x, axis = 0)
median = np.mean(x, axis = 0)
std_dev = np.std(x, axis = 0)
variance = np.var(x, axis = 0)

print('\nMean: ', mean)
print('Median: ', median)
print('Std Deviation: ', std_dev)
print('Variance: ', variance)

max_var_index = np.argmax(variance)

feature_names = iris.feature_names

print('\nFeature with maximum variance: ', feature_names[max_var_index])
print('Value of maximum variance: ', variance[max_var_index])


feature = x[:, 0]
print('original shape: ', feature.shape)

reshaped_feature= feature.reshape(-1,1)
print('reshaped shape: ', reshaped_feature.shape)

#print(feature)
#print(reshaped_feature)


Mean:  [5.84333333 3.05733333 3.758      1.19933333]
Median:  [5.84333333 3.05733333 3.758      1.19933333]
Std Deviation:  [0.82530129 0.43441097 1.75940407 0.75969263]
Variance:  [0.68112222 0.18871289 3.09550267 0.57713289]

Feature with maximum variance:  petal length (cm)
Value of maximum variance:  3.0955026666666674
original shape:  (150,)
reshaped shape:  (150, 1)


Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [61]:
samples = x[:100, 2:4]

mean_petal_length = np.mean(x[:, 2])

filter_cond = x[:,2] > mean_petal_length

filetered_samples = x[filter_cond]

print('Selected Samples: ', len(filetered_samples))

# used to select important data that we can use for training

Selected Samples:  93


Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [62]:
x_scaled = (x - mean) / std_dev
x_scaled_mean = np.mean(x_scaled, axis = 0)
x_scaled_std_dev = np.std(x_scaled, axis = 0)

print('x_scaled_mean: ', x_scaled_mean)
print('x_scaled_std_dev: ', x_scaled_std_dev)

x_scaled_mean:  [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
x_scaled_std_dev:  [1. 1. 1. 1.]


Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [63]:
import seaborn as sns

df = sns.load_dataset('titanic')

print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

print(df.isnull().sum())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [64]:
condition = (df['sex'] == 'female') & (df['class'] == 'First')
female_1st = df[condition]
female_1st_survival_rate = female_1st['survived'].mean()
overall_survival_rate = df['survived'].mean()

print('female_1st_survival_rate=', female_1st_survival_rate)
print('overall_survival_rate=', overall_survival_rate)

# female in first class has high chance of survivial



female_1st_survival_rate= 0.9680851063829787
overall_survival_rate= 0.3838383838383838


Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [65]:
df['age'].fillna(df['age'].median(), inplace=True)

df['embarked'].fillna(df['age'].mode(), inplace=True)

df.drop(columns=['deck'], inplace=True)

C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\1005769592.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\1005769592.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exa

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [75]:
df['family_size'] = df['sibsp'] + df['parch'] + 1
df['is_alone']=(df['family_size'] == 1).astype(int)
survival_rate_alone = df.groupby('is_alone')['survived'].mean()
print(survival_rate_alone)

is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64


Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [89]:
tips = sns.load_dataset('tips')

print(tips.groupby('day')['tip'].mean())
print(tips.groupby('sex')['total_bill'].sum())

tips['tip_percentage']  = tips['tip']*100/tips['total_bill']
print("\n")
print(tips.groupby('day')['tip_percentage'].mean().idxmax())

# this helps in segmentation of customers

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64


Fri


C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\3252220367.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips.groupby('day')['tip'].mean())
C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\3252220367.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips.groupby('sex')['total_bill'].sum())
C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\3252220367.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [92]:
condition = (tips['total_bill'] > 20) & (tips['tip'] < 3)
cols = ['total_bill', 'tip', 'sex']
segment_data = tips[condition][cols]
segment_data.groupby('sex')['tip'].mean()

C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\2256806309.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  segment_data.groupby('sex')['tip'].mean()


sex
Male      2.060769
Female    2.478750
Name: tip, dtype: float64

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [100]:
x = np.array([[1,3], [4,5], [7,9]])
y = np.array([[11,13], [41,15], [17,19]])
vstack = np.vstack((x,y))
hstack=np.hstack((x,y))
print(hstack)
print(vstack.shape)
print(hstack.shape)

reshaped = hstack.reshape(2,6)

print(reshaped)

[[ 1  3 11 13]
 [ 4  5 41 15]
 [ 7  9 17 19]]
(6, 2)
(3, 4)
[[ 1  3 11 13  4  5]
 [41 15  7  9 17 19]]


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [101]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# 1. Load dataset
df = sns.load_dataset('titanic')

# 2. Select relevant columns (important step)
df = df[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']]

# 3. Handle missing values

# Numerical → fill with median
df['age'].fillna(df['age'].median(), inplace=True)
df['fare'].fillna(df['fare'].median(), inplace=True)

# Categorical → fill with mode
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

# 4. Encode categorical variables

# sex → binary encoding
df['sex'] = df['sex'].map({'male': 0, 'female': 1})

# embarked → one-hot encoding
df = pd.get_dummies(df, columns=['embarked'], drop_first=True)

# 5. Separate features and target
X = df.drop('survived', axis=1)
y = df['survived']

# 6. Normalize numerical features
scaler = StandardScaler()

num_cols = ['age', 'fare', 'sibsp', 'parch']
X[num_cols] = scaler.fit_transform(X[num_cols])

# 7. Convert to NumPy array
X_final = X.values
y_final = y.values

# 8. Output
print("Feature Matrix Shape:", X_final.shape)
print("Target Shape:", y_final.shape)

print("\nSample Features:\n", X_final[:5])
print("\nSample Target:\n", y_final[:5])

Feature Matrix Shape: (891, 8)
Target Shape: (891,)

Sample Features:
 [[3 0 -0.5657364610748746 0.4327933656785018 -0.4736736092984604
  -0.5024451714361923 False True]
 [1 1 0.6638610320657843 0.4327933656785018 -0.4736736092984604
  0.7868452935884461 False False]
 [3 1 -0.2583370877897099 -0.47454519624983954 -0.4736736092984604
  -0.4888542575852486 False True]
 [1 1 0.4333115021019107 0.4327933656785018 -0.4736736092984604
  0.4207302360686478 False True]
 [3 0 0.4333115021019107 -0.47454519624983954 -0.4736736092984604
  -0.4863374216869257 False True]]

Sample Target:
 [0 1 1 1 0]


C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\1832863916.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
C:\Users\atanu\AppData\Local\Temp\ipykernel_3396\1832863916.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For e

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Correlation matrix
corr_matrix = df.corr()

print(corr_matrix)

# Threshold for high correlation
threshold = 0.9

high_corr_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > threshold:
            col1 = corr_matrix.columns[i]
            col2 = corr_matrix.columns[j]
            high_corr_pairs.append((col1, col2))

print("Highly correlated feature pairs:")
print(high_corr_pairs)

# Drop one feature from correlated pair
df_reduced = df.drop(columns=['petal width (cm)'])

print("Original shape:", df.shape)
print("Reduced shape:", df_reduced.shape)

# highly correlated feature means duplicate information. Model sees same signal twice

                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  
Highly correlated feature pairs:
[('petal width (cm)', 'petal length (cm)')]
Original shape: (150, 4)
Reduced shape: (150, 3)


Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [13]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

# Keep relevant columns
df = df[['age', 'survived']]


def age_category(age):
    if pd.isnull(age):
        return 'Unknown'
    elif age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(age_category)

print(df[['age', 'age_group']].head())

survival_by_group = df.groupby('age_group')['survived'].mean()

print(survival_by_group)

# children has highest survival likelihood

    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
age_group
Adult      0.386087
Child      0.539823
Senior     0.269231
Unknown    0.293785
Name: survived, dtype: float64


Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [17]:
import numpy as np

np.random.seed(42)

# Generate 1000 random errors (normal distribution)
errors = np.random.normal(loc=0, scale=1, size=1000)

mean_error = np.mean(errors)
std_error = np.std(errors)

print("Mean Error:", mean_error)
print("Standard Deviation:", std_error)


lower_bound = mean_error - 2 * std_error
upper_bound = mean_error + 2 * std_error

outliers = errors[(errors < lower_bound) | (errors > upper_bound)]

print("Outliers count:", len(outliers))
print("Sample outliers:", outliers[:10])

# high variance means model predictions are inconsistent, sometimes accurrate, sometimes inconsistent

Mean Error: 0.01933205582232549
Standard Deviation: 0.9787262077473543
Outliers count: 44
Sample outliers: [-1.95967012 -2.6197451  -1.98756891  2.46324211  2.19045563  2.72016917
  3.85273149  2.31465857  2.14394409 -2.02514259]


Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [23]:
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

# Create tip percentage
tips['tip_percentage'] = (tips['tip'] / tips['total_bill']) * 100

print(tips.head())

grouped = tips.groupby(['day', 'time']).agg({
    'total_bill': 'sum',
    'tip': 'sum',
    'tip_percentage': 'mean'
}).reset_index()

print(grouped)

# Highest revenue based on total_bill
top_segment = grouped.loc[grouped['total_bill'].idxmax()]

print("Highest Revenue Segment:\n", top_segment)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765
    day    time  total_bill     tip  tip_percentage
0  Thur   Lunch     1077.55  168.83       16.130074
1  Thur  Dinner       18.78    3.00       15.974441
2   Fri   Lunch       89.92   16.68       18.876489
3   Fri  Dinner      235.96   35.28       15.891611
4   Sat   Lunch        0.00    0.00             NaN
5   Sat  Dinner     1778.40  260.40       15.315172
6   Sun   Lunch        0.00    0.00             NaN
7   Sun  Dinner     1627.16  247.39       16.689729
Highest Revenue Segment:
 day                     Sat
time                 Dinner
total_bill           1778.4
ti

C:\Users\atanu\AppData\Local\Temp\ipykernel_12328\1321972042.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = tips.groupby(['day', 'time']).agg({
